version: 0.2
phases:
  install:
    commands:
      - echo "[INFO] [INSTALL] Installing dependencies"
      - pip install git-remote-codecommit
      - echo "[INFO] [INSTALL] Installing finished"
      - wget https://releases.hashicorp.com/terraform/1.6.4/terraform_1.6.4_linux_amd64.zip
      - unzip terraform_1.6.4_linux_amd64.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform
    finally:
      - terraform --version
  build:
    commands:
      - cd terraform
      - chmod +x resolve_permission_sets_and_assignments.py
      - python3 resolve_permission_sets_and_assignments.py
      - terraform init 
      - terraform plan
      - terraform apply -auto-approve